"""empty message

Revision ID: 3360c60dc65f
Revises: 9b4a54d73efa
Create Date: 2021-08-05 15:08:37.883368

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3360c60dc65f'
down_revision = '9b4a54d73efa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pins', 'notes')
    op.drop_column('pins', 'cookies_available')
    op.drop_column('pins', 'pinned_at')
    op.drop_column('pins', 'upvote_count')
    op.drop_column('pins', 'hours')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pins', sa.Column('hours', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('pins', sa.Column('upvote_count', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('pins', sa.Column('pinned_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('pins', sa.Column('cookies_available', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('pins', sa.Column('notes', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
