"""empty message

Revision ID: 5ed03e0c9ab8
Revises: 3360c60dc65f
Create Date: 2021-08-09 14:05:52.445896

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ed03e0c9ab8'
down_revision = '3360c60dc65f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pins', sa.Column('notes', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pins', 'notes')
    # ### end Alembic commands ###
