"""empty message

Revision ID: ae632899ffbe
Revises: 
Create Date: 2021-08-18 00:57:09.105182

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae632899ffbe'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pins',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('lat_lon', sa.String(), nullable=True),
    sa.Column('pinned_at', sa.DateTime(), nullable=True),
    sa.Column('hours', sa.String(), nullable=True),
    sa.Column('cookies_available', sa.String(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pins')
    # ### end Alembic commands ###
