"""empty message

Revision ID: d702285916f3
Revises: 4da685e23675
Create Date: 2021-08-11 14:50:11.859902

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd702285916f3'
down_revision = '4da685e23675'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pins', sa.Column('hours', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pins', 'hours')
    # ### end Alembic commands ###
