"""empty message

Revision ID: ec39be5f81f4
Revises: d702285916f3
Create Date: 2021-08-17 19:45:14.033468

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec39be5f81f4'
down_revision = 'd702285916f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pins', sa.Column('cookies_available', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pins', 'cookies_available')
    # ### end Alembic commands ###
